name: Development.yml Cleanup CI
on:
  pull_request:
    types: [closed]

jobs:
  pre_destroy:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET_NAME: thomasamendez-vue-dev
    outputs:
      bucket_name: ${{ steps.bucket_name.outputs.bucket }}
      bucket_name_storybook: ${{ steps.bucket_name_storybook.outputs.storybook }}
    steps:
      - name: "Create bucket_name_suffix Output"
        id: bucket_name_suffix
        run: |
          suffix=$(echo ${{ github.head_ref }} | sed 's/\//-/')
          echo "::set-output name=suffix::$suffix"

      - name: "Create bucket_name Output"
        id: bucket_name
        run: |
          bucket_name=$(echo ${{ env.AWS_BUCKET_NAME }}-${{ steps.bucket_name_suffix.outputs.suffix }})
          echo "::set-output name=bucket::$bucket_name"

      - name: "Create bucket_name_storybook Output"
        id: bucket_name_storybook
        run: |
          storybook=$(echo ${{ steps.bucket_name.outputs.bucket }}-storybook)
          echo "::set-output name=storybook::$storybook"

  dev-destroy-s3-dev:
    runs-on: ubuntu-latest
    needs: pre_destroy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format - Destroy Existing Bucket
        id: fmt-destroy
        run: terraform -chdir=terraform/development/destroy fmt -check

      - name: Terraform Init - Destroy Existing Bucket
        id: init-destroy
        run: terraform -chdir=terraform/development/destroy init -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Validate - Destroy Existing Bucket
        id: validate-destroy
        run: terraform -chdir=terraform/development/destroy validate -no-color

      - name: Terraform Plan - Destroy Existing Bucket
        id: plan-destroy
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          terraform -chdir=terraform/development/destroy plan -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name }}" -no-color

      - name: Terraform Apply - Destroy Existing Bucket
        id: apply-destroy
        if: steps.plan-destroy.outcome == 'success'
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          terraform -chdir=terraform/development/destroy import -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name }}" aws_s3_bucket.bucketdev ${{ needs.pre_destroy.outputs.bucket_name }}
          terraform -chdir=terraform/development/destroy apply -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name }}" -auto-approve
          terraform -chdir=terraform/development/destroy destroy -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name }}" -auto-approve

  dev-destroy-s3-dev-storybook:
    runs-on: ubuntu-latest
    needs: pre_destroy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          # terraform_version: 0.13.0:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format - Destroy Existing Bucket
        id: fmt-destroy
        run: terraform -chdir=terraform/development/destroy fmt -check

      - name: Terraform Init - Destroy Existing Bucket
        id: init-destroy
        run: terraform -chdir=terraform/development/destroy init -backend-config="region=${{ secrets.AWS_REGION }}" -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Validate - Destroy Existing Bucket
        id: validate-destroy
        run: terraform -chdir=terraform/development/destroy validate -no-color

      - name: Terraform Plan - Destroy Existing Bucket
        id: plan-destroy
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          terraform -chdir=terraform/development/destroy plan -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name_storybook }}" -no-color

      - name: Terraform Apply - Destroy Existing Bucket
        id: apply-destroy
        if: steps.plan-destroy.outcome == 'success'
        run: |
          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
          terraform -chdir=terraform/development/destroy import -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name_storybook }}" aws_s3_bucket.bucketdev ${{ needs.pre_destroy.outputs.bucket_name_storybook }}
          terraform -chdir=terraform/development/destroy apply -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name_storybook }}" -auto-approve
          terraform -chdir=terraform/development/destroy destroy -var="aws_bucket_name=${{ needs.pre_destroy.outputs.bucket_name_storybook }}" -auto-approve
